# Generated by Django 2.1 on 2019-05-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190525_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='rating',
        ),
    ]
