# Generated by Django 2.1 on 2019-05-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_field_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='projects',
            field=models.ManyToManyField(to='dashboard.Project'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='dashboard.Field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dashboard.Attribute'),
        ),
    ]
