# Generated by Django 2.1 on 2019-05-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190525_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['rating']},
        ),
        migrations.AlterField(
            model_name='criterion',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='criteria', to='dashboard.Project'),
        ),
    ]
