# Generated by Django 2.1 on 2019-05-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='improvement_message',
            field=models.CharField(default='Improve', max_length=200),
            preserve_default=False,
        ),
    ]
